stages:
- generate
- deploy

generate:
 image: $PELICANIMAGE
 stage: generate
 artifacts:
  paths:
    - /builds/$COMPILATIONPATH/output
 script:
  - cd /builds/$COMPILATIONPATH
  - pelican content -o output -s pelicanconf.py
  - weasyprint output/cv output/cv.pdf --base-url https://maxime.sourdin.ovh
 tags:
  - docker

deployblog:
 image: $AWSCLIIMAGE
 stage: deploy
 artifacts:
  when: always
  expire_in: 20 minutes
  paths:
   - /builds/$COMPILATIONPATH/output
 script:
  - aws s3 cp --content-type 'text/html' /builds/$COMPILATIONPATH/output/ s3://${BUCKET_NAME}/ --recursive
 environment:
  name: ${CI_COMMIT_REF_SLUG}
  url: https://${BUCKET_NAME}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/
 tags:
  - docker
 allow_failure: true
