stages:
- deploy

pages:
 image: $PELICANIMAGE
 stage: deploy
 artifacts:
  paths:
    - public/
 script:
  - cd /builds/$COMPILATIONPATH
  - /home/python/.local/bin/pelican content -o public -s pelicanconf.py
#  - python3 generatepdf.py
 tags:
  - docker
