stages:
- html
- deployhtml
- pdf
- deploypdf

generate:
 image: $PELICANIMAGE
 stage: html
 artifacts:
  paths:
    - /builds/$COMPILATIONPATH/public
 script:
  - cd /builds/$COMPILATIONPATH
  - /home/python/.local/bin/pelican content -o public -s pelicanconf.py
#  - python3 generatepdf.py
 tags:
  - docker
